services:
  imageFrontend:
    container_name: frontend-docker
    build: ./imageFrontend
    image: raulmoya/trabajo-final-dockerfrontend:v2.0.0
    ports:
      - '3000:3000'

  imageBackend:
    container_name: backend-docker
    build: ./imageBackend
    image: raulmoya/trabajo-final-dockerbackend:v2.0.0
    ports:
      - '8080:8080'
  
